name: Deploy Front

on:
  push:
    branches:
      - 'dev'
      - 'main'

jobs:
  build:
    runs-on: ubuntu-20.04
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push app Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sc-kpi-web:${{ github.ref_name }}
          build-args: |
            GA_ID=${{ vars.GA_ID }}
            NEXT_PUBLIC_API_KEY=${{ vars.NEXT_PUBLIC_API_KEY }}
            NEXT_PUBLIC_API_BASE_URL=${{ vars.NEXT_PUBLIC_API_BASE_URL }}
            NEXT_PUBLIC_CAMPUS_API_BASE_URL=${{ vars.NEXT_PUBLIC_CAMPUS_API_BASE_URL }}
            NEXT_PUBLIC_TINYMCE_API_KEY=${{ vars.NEXT_PUBLIC_TINYMCE_API_KEY }}
            NEXT_PUBLIC_MONOBANL_JAR_URL=${{ vars.NEXT_PUBLIC_MONOBANL_JAR_URL }}
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: 0
