name: Build

on:
  pull_request:
    branches:
      - 'dev'
      - 'main'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push app Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            ENV=${{ github.ref_name == 'main' && 'production' || 'development' }}
          tags: srkpi/sc-kpi-web
